---
# Create a 2x2 gluster volume
- name: Setup backend and create a GlusterFS cluster
  hosts: all
  remote_user: root
  gather_facts: true
  roles:
    - gluster_install
    - gluster.infra
    - gluster.cluster
    - common
