version: '3.3'

services:
  influxdb:
    image: influxdb
    hostname: influxdb
    volumes:
      - influx-config:/etc/influxdb
      - influx-data:/var/lib/influxdb

  nodered:
    image: nodered/node-red
    hostname: nodered
    volumes:
      - nodered-config:/data
    ports:
      - 1880:1880
    extra_hosts:
      - nodered.docker.demo:127.0.0.1
    dns:
      - 10.8.8.120

  grafana:
    image: grafana/grafana
    hostname: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,pierosavi-imageit-panel,grafana-worldmap-panel,grafana-piechart-panel,farski-blendstat-panel,natel-discrete-panel,blackmirror1-singlestat-math-panel,flant-statusmap-panel,snuids-trafficlights-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - grafana-log:/var/log/grafana

networks:
  default:
    external: 
      name: gin_network

volumes:
  influx-data:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/influx-data
      o: bind
  influx-config:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/influx-config
      o: bind
  nodered-data:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/nodered-data
      o: bind
  nodered-config:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/nodered-config
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/grafana-data
      o: bind
  grafana-config:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/grafana-config
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/grafana-data
      o: bind
  grafana-log:
    driver: local
    driver_opts:
      type: none
      device: /data/stacks/gin/volumes/grafana-log
      o: bind