---
- name: Set Hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ domain_name }}"

- name: Set Timezone
  timezone:
    name: Europe/Prague
  tags: timezone
  
- name: Copy CA Certificates
  copy:
    src: "{{ certs_folder | default('') }}{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ca_certs }}"
  register: ca_status

- name: Update CA TrustStore
  command:
    cmd: update-ca-certificates --fresh
  when:
    - ca_status.changed

- name: Install Required Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-apt
    - python3-pip