---
- name: Set Hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ domain_name }}"

- name: Set Timezone
  timezone:
    name: Europe/Prague
  tags: timezone
  
- name: Copy CA Certificates
  copy:
    src: "{{ certs_folder | default('') }}{{ item }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ca_certs }}"
  register: ca_status

- name: Update CA TrustStore
  command:
    cmd: update-ca-trust extract
  when:
    - ca_status.changed
#- name: Create Directories
#  file:
#    path: "{{ item }}"
#    state: directory
#  loop:
#    - "/data"
#    - "/etc/systemd/system/srv.mount.d/"
#
#- name: Copy Magic File
#  copy:
#    src: magic
#    dest: /etc/systemd/system/srv.mount.d/override.conf
#
#- name: Mount GlusterFS
#  mount:
#    path: /data
#    src: "localhost:/gluster_volume1"
#    fstype: glusterfs
#    opts: defaults,_netdev
#    state: present
